language: node_js
node_js:
- '4'
- '6'
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
    # Install peerDependencies on > npm3
    # When all dependencies declare bitcore-lib as a peerDependency this can be bumped up, but this matches the current ecosystem version expected by dependencies
  - if [ $(npm --version | sed 's/\..*//g') -ge 3 ]; then npm install bitcore-lib@0.13.7; fi
  - npm install
after_script:
  - gulp coveralls
